title       = "twominutepapers"
baseURL     = "https://twominutepapers-cli.tamnd.com/"
description = "A command line for twominutepapers."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/twominutepapers-cli"
